### ISSUE TITLE
Add VirtualBox as Hypervisor

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2-diagnostics#1]

**Comment by widhalmt** [comment]
I found at least some boxes which have the following output of `virt-what`:

    virtualbox

So it seems to depend how the box was built. Still need more input.

Maybe someone could bring light into this? Running `virt-what` on VirtualBox VMs other than CentOS 7 would be helpful, too.

**Comment by wnieder** [comment]
VMs created using VirtualBox returns "virtualbox" (Debian 9.3.0, Ubuntu 16.10.3).
Looking into virt-what this is dependent on inspecting the manufacturer code returned by executing dmidecode.

**Comment by widhalmt** [comment]
I tested this on other boxes as well. As @wnieder said, it depends on what dmidecode says. I'd say the check should be sufficient for now.

If it's not, please reopen this issue or open a new one about hypervisor detection being flawed.
