### ISSUE TITLE
Mask passwords in output

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2-diagnostics#16]
In standard output there are some passwords (e.g. Api Users). Mask them as a default.
Think about adding an option to have them in clear text though.

**Comment by larsengels** [comment]
You can mask the password like this:
`
sed '/password/s/"[^"]*"/SECRET/' /usr/local/etc/icingaweb2/modules/monitoring/commandtransports.ini
`

**Comment by widhalmt** [comment]
Thank you. I know. It's just that I open an issue whenever I have an idea what I could implement later and write it later (including testing, and so on), even for simple oneliners. 

Although I might just have use a `grep -v` ;-)
