### ISSUE TITLE
Add VMware as Hypervisor

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2-diagnostics#2]
Could someone please run `virt-what` on a VMware Guest (Linux) and enter the output in this issue?

**Comment by wolf-in-sheeps-clothing** [comment]
Ubuntu Server 16.04 x64 (Guest) VMware ESXi 6.5.0 (Host)

root@xxxx:~# virt-what
vmware

I hope this is what you need.

**Comment by widhalmt** [comment]
Thank you! This is what I needed. I'll build it into the script asap.
