### ISSUE TITLE
cat: /etc/redhat-release: No such file or directory

### ISSUE THREAD

**Issue by l13t** [Icinga/icinga2-diagnostics#20]
> OS Version: cat: /etc/redhat-release: No such file or directory
> Ubuntu
> 14.04
> Hypervisor: Running on hardware or unknown hypervisor
> CPU cores: 12
> RAM: 20G
> Firewall: active

Checked script on Ubuntu machine

**Comment by l13t** [comment]
I'll work on this.

**Comment by widhalmt** [comment]
Thanks, but this is a partial duplicate of #12 :-) I'll look into the PR right away.

**Comment by l13t** [comment]
Well. It's not about duplicate. It's more to fix an issue with redhat-release file check. Because you checked if it exists in not really correct way.

**Comment by widhalmt** [comment]
Yes, it was the wrong way to check. So this might be a good start for implementing checks for new plattforms as well.
