### ISSUE TITLE
Get "Director" version

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2-diagnostics#32]
This is a thing we see very often in support.

Since there are no packages for director right now, there are different ways to get Director installed and sometimes it's hard for support engineers and even the user to determine the current version.

Possible ways of installation I can think of:

* `git clone`
* `git clone` with `checkout` of specific tag or release
* Download of specific release
* Download of master as zip file which leaves us with a some random commit

**Comment by widhalmt** [comment]
Pinging @Thomas-Gelf : Can you think of any way to determine the version of the used director if someone just downloads the master as a zipfile?

There's no .git directory and icingacli just shows "master" as version. The first version of the check might just say "zipfile download detected, can not determine version"

**Comment by widhalmt** [comment]
Although I closed this issue we can still reopen if it someone finds a way to determine the version of a downloaded "master" archive from any time.

**Comment by Thomas-Gelf** [comment]
@widhalmt: this is not possible, unlike others GitHub doesn't place a hidden file or similar into the archive. It however puts the revision into the ZIP file header, so as long as you still have the downloaded ZIP archive you can determine the version as follows:

```
user@host:~$ wget -q https://github.com/Icinga/icingaweb2-module-director/archive/master.zip
user@host:~$ unzip -z master.zip 
Archive:  master.zip
39ce02b1e5c64cb2e605b7b24d6811e144a9b54c
```

The SHA1 checksum [39ce02b](https://github.com/Icinga/icingaweb2-module-director/commit/39ce02b1) corresponds to the current master. This however doesn't help in your use-case, with extracted files that finished in some magic way on a random server.

Cheers,
Thomas

**Comment by widhalmt** [comment]
Thanks a lot for the information. As you said, your tip doesn't help with this usecase.
The only way I can think of is checksumming the whole directory which is no feasable way because people might change a bit and we needed the checksums of every commit.
But that's ok for me. At least we can detect when someone used zip download so we can tell them to switch to a release.
Thanks again, this ties one more lose end.

Cheers,
Thomas
