### ISSUE TITLE
Check Timezone settings in php

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2-diagnostics#34]
Make sure to check the setting that's actually used, especially with FPM

**Comment by wnieder** [comment]
Depending on the installation there may be more than one php.ini files so one way might be to output all files:

```
echo ""
echo "FPM:"
ps -ef| grep httpd | grep -v grep | cut -c49- | sort -u | while IFS=\/ read line
do
   CFG=`echo $line | sed 's/.* //'`
   ls -l $CFG 2>/dev/null
   $line -M 2>/dev/null | grep -i fpm
   echo
done

echo ""
echo "PHP:"
find / -name php.ini 2>/dev/null | while IFS=\/ read line
do
   ls -l $line 2>/dev/null
   grep "^date" $line
   echo
done
```

**Comment by widhalmt** [comment]
Hm, thanks for the code, @wnieder . But fpm doesn't show in the list of modules. I'm quite sure, we need a bit more tricks to verify that fpm is running and httpd is actually using it.

I'll add parts of your code for verifying timezone settings, though.
