### ISSUE TITLE
pushd and popd error on Ubuntu

### ISSUE THREAD

**Issue by wolf-in-sheeps-clothing** [Icinga/icinga2-diagnostics#56]
Ubuntu Server 16.04.5 x64
Diagnostic Script: Master via Git Clone / Pull

I've got the following error:

Director is a git clone with the following last commit

/usr/share/diagnostics-icinga2/icinga-diagnostics.sh: 253: /usr/share/diagnostics-icinga2/icinga-diagnostics.sh: pushd: not found
/usr/share/diagnostics-icinga2/icinga-diagnostics.sh: 254: /usr/share/diagnostics-icinga2/icinga-diagnostics.sh: popd: not found

After adjusting the line "#!/bin/sh" to "#!/bin/bash" in the script, the output is OK

Director is a git clone with the following last commit

commit f3b972e90402bf0be07f81ade37b7bd3eea56391
Author: Thomas Gelf <thomas@gelf.net>
Date:   Wed Nov 7 11:03:38 2018 +0100

    Clone..Form: fix for ImportSource and SyncRule

**Comment by widhalmt** [comment]
Thanks for pointing this out. We might have to replace pushd and popd.

Initially we were using `bash` instead of `sh` but we made the switch to support other icinga-supported OS'es like FreeBSD.
