### ISSUE TITLE
Make icinga2-diagnostics part of Icinga2?

### ISSUE THREAD

**Issue by jenslink** [Icinga/icinga2-diagnostics#57]
Hi,

I would like to see this script as part of the Icinga2 package so I don't need to manualy copy this to a system if I need to run it. Some few line in the official documentation would also be great.

Jens

**Comment by widhalmt** [comment]
Hi,

We'll discuss this and see what we can do.

Would it be ok if there was an icinga2-diagnostics package in the Icinga 2 repository so you could install it alongside Icinga 2?

Cheers,
Thomas

**Comment by dnsmichi** [comment]
I like the way it can be fetched independently. Once it is bundled in another package (icinga2 or icingaweb2), this needs a point release to update the diagnostics script. The past tells me that this isn't the best idea.

Depending on the involved scripts I would create a package, nor not. If it is just this shell script, a simple curl/wget is sufficient imho (and one can automate this with Puppet for instance).

Cheers,
Michael

**Comment by widhalmt** [comment]
We talked about how to distribute Diagnostics and devided we'd go for a seperate package. I'll close this issue in favor of #80 .
