### ISSUE TITLE
Set & release a version

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2-diagnostics#59]
Dumped outputs contain `Version: 0.0` which seems odd. Thanks.

https://github.com/Icinga/icinga2-diagnostics/blob/d61dd59713a443217a6f973ad45d27eaf65a95ca/icinga-diagnostics.sh#L7

**Comment by dnsmichi** [comment]
Oh, and with the removal of 1.x, we might rename the repository to `icinga-diagnostics` as well as inside the docs.

**Comment by widhalmt** [comment]
I wanted to wait for 0.1 to set a version. I hoped that this would be anytime soon - back then. ;-) But I'm positive I'll manage to get a release into the wild in reasonable time. Maybe I'll have to postpone one or another issue.

**Comment by widhalmt** [comment]
I don't see any problem with the renaming. Thanks for the heads up.

**Comment by dnsmichi** [comment]
0.x versions should be considered for pre-release tests and alpha/beta things, just with a different name ;-) Our modules, plugins and RT/Pretix extensions follow the 0.x.y principle as well, reaching 1.x.y in their first official release :)

**Comment by widhalmt** [comment]
I wanted to follow the x.y.z approach but thought the script not to be usable at all. The fact that it got adopted already caught me a bit off guard and I didn’t want to change the version number just so. ;-) After 0.1.0 I’ll follow the same policy like our other tools.
