### ISSUE TITLE
-t silently fails if bzip2 is not installed

### ISSUE THREAD

**Issue by bengelberth-shadowsoft** [Icinga/icinga2-diagnostics#75]
When running the diagnostics with -t flag on a system without bzip2 the script creates the tar archive with a filesize of 0 and gives no indication of an error.

https://github.com/Icinga/icinga2-diagnostics/blob/master/icinga-diagnostics.sh#L474 sends stderr to devnull and does not check the rc of the command.

A possible solution would be to check the rc, remove the tarball on failure, and try to create a tarball using different compression (like gzip).  Or at least print an error to the user and remove the 0 byte archive file.

**Comment by widhalmt** [comment]
Hi thanks for letting us know. We'll add some error handling.

**Comment by widhalmt** [comment]
/ref/IC/13773
